/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,svelte,js,ts}'],
  theme: {
    extend: {},
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
  daisyui: {
    themes:
    [
      "dark",
      // "light",
      // "corporate",
      // "night",
      // "cupcake",
      // "cyberpunk",
      // "sunset",
    // "bumblebee",
    // "emerald",
    // "synthwave",
    // "retro",
    // "valentine",
    // "halloween",
    // "garden",
    // "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    // "fantasy",
    // "wireframe",
    // "black",
    // "luxury",
    // "dracula",
    // "cmyk",
    // "autumn",
    // "business",
    // "acid",
    // "lemonade",
    // "coffee",
    // "winter",
    // "dim",
    // "nord",
    ]
  },
}
